version: "2"

services: 
  web:
    image: tjcarskadon/hello
    ports:
      - 80:8000
  api: 
    image: tjcarskadon/digitalkapi
    command: bash -c 'while ! </dev/tcp/db/5432; do sleep 1; done; nodal db:prepare && nodal db:migrate && nodal db:seed && nodal s;'
    ports: 
      - 3333:3333
    links:
      - db
    environment:
      - NODE_ENV=production 
      - PORT=3333
      - DATABASE_HOST=db
      - DATABASE_USER=digitalk 
      - DATABASE_PASSWORD=digitalkapi
      - DATABASE_PORT=5432
      - DATABASE_DB=digidb
      - DATABASE_URL=postgres://digitalk:digitalkapi@db:5432/digidb
  db:
    image: postgres
    environment:
      - POSTGRES_USER=digitalk
      - POSTGRES_PASSWORD=digitalkapi
      - POSTGRES_DB=digidb